config/routes.rb
SkintDance::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/day_tickets/closed" => "day_ticket_orders#closed", as: :day_tickets_closed
  
  resources :day_ticket_orders, path: "day_tickets" do
  end

  resources :reservations do
    get :success
  end

  resources :pre_reservations do
    get :success
  end

  # get "reservations/success/:reference" => "reservations#success", as: "reservation_success"

  match ':action', controller: :pages
  root :to => 'pages#index'
end

app/models/pre_reservation.rb
class PreReservation < ActiveRecord::Base
  attr_accessible :email, :name, :reference, :resource_category, :expires_at

  has_one :reservation, foreign_key: :reference, primary_key: :reference

  attr_accessor :how_many

  validates_presence_of :name, :email, :reference, :resource_category, :expires_at
  validates_email_format_of :email

  def self.unredeemed
    where("not exists(select * from reservations where reservations.reference=pre_reservations.reference)")
  end

  def self.unexpired(clock = Time.zone)
    where("expires_at > ?", clock.now)
  end


  def waiting_list?
    
  end

  def expired?
    Time.zone.now > expires_at
  end

  def used_by
    Reservation.where(reference: self.reference).first
  end
end

app/controllers/pre_reservations_controller.rb
class PreReservationsController < ApplicationController
  before_filter :find_reservation, only: :success
  before_filter :captcha_valid?, only: :create

  def index
    if Time.zone.now < Time.zone.parse(ReservationManager::SALES_OPEN)
      redirect_to "/"
    end
  end

  def create
    pre_reservation_params = params[:pre_reservation]
    pre_reservation_params[:how_many] = pre_reservation_params[:how_many].to_i
    @pre_reservations = RESERVATION_MANAGER.pre_reserve(pre_reservation_params)
    if @pre_reservations.all? { |p| p.errors.empty? }
      @pre_reservations.each do |pre_reservation|
        PreReservationAcknowledgement.acknowledge(pre_reservation).deliver
      end
      redirect_to pre_reservation_success_path(@pre_reservations.first.reference, references: @pre_reservations.map(&:reference))
    else
      @pre_reservation = @pre_reservations.first
      render :index
    end
  end

  def success
    @pre_reservations = params.fetch(:references, [params[:pre_reservation_id]]).map do |ref|
      PreReservation.find_by_reference(ref)
    end

    if @pre_reservations.size == 1
      render "success_one_place"
    elsif @pre_reservations.size == 2
      render "success_two_places"
    else
      redirect_to pre_reservations_path
    end
    # if @pre_reservation.waiting_list?
    #   render :waiting_list
    # end
  end

private
  def find_reservation
    @pre_reservation = PreReservation.find_by_reference(params[:pre_reservation_id])
    if !@pre_reservation
      redirect_to pre_reservations_path, :notice => "Sorry, can't find that reservation"
    end
  end

  def captcha_valid?
    if ! verify_recaptcha
      pre_reservation.valid?
      pre_reservation.errors.delete(:reference)
      pre_reservation.errors.delete(:expires_at)

      pre_reservation.errors[:base] << "Spam control check failed"
      render :index
    end
  end

  def pre_reservation
    @pre_reservation ||= PreReservation.new(params[:pre_reservation])
  end

  helper_method :pre_reservation
end

app/views/pre_reservations/index.html.erb
<section class="pre-reservations">
  <div class="page-header">
    <h1>Request a place at Skint 2014</h1>
    <h3>31st October - 3rd November 2014, Ashover, Derbyshire</h3>
  </div>

  <h2>Pre-reservations</h2>
  <% if pre_reservation.errors.any? %>
  <div class="controls alert alert-block">
    <h4>Error</h4>
    <%= pre_reservation.errors.full_messages.to_sentence %>
  </div>
  <% end %>

  <% if flash[:errors].present? %>
  <div class="controls alert alert-block">
    <h4>Error</h4>
    <%= flash[:errors] %>
  </div>
  <% end %>


  <div class="intro">
    <p>
      We're trying a &ldquo;pre-reservation&rdquo; system this year, so that you don't 
      have to rush when filling out the reservation form.
    </p>

    <p>
      Your pre-reservation does not guarantee you a place at Skint. It
      simply confirms your place in the queue!
    </p>
    <p class="img">
      <%= image_tag 'ticket_dispenser.jpg' %>
    </p>
  </div>

  <h2 class="form-header">Make your pre-reservation</h2>

<%= bootstrap_form_for(pre_reservation, html: { class: 'form-horizontal' }) do |f|%>
  <% if f.object.errors.any? %>
  <div class="controls alert alert-block">
    <h4>Error</h4>
    <%= f.object.errors.full_messages.to_sentence %>
  </div>
  <% end %>

  <% if flash[:errors].present? %>
  <div class="controls alert alert-block">
    <h4>Error</h4>
    <%= flash[:errors] %>
  </div>


  <% end %>
  <%= f.text_field :name, label: "Your name" %>
  <%= f.text_field :email %>
  <%= f.select :resource_category, {label: "Sleeping where?", "in the hall" => :sleeping, "camping/own accomodation" => :non_sleeping } %>
  <%= f.select(:how_many, {label: "How many places?", "One" => "1", "Two" => "2"}) %>

  <div class="control-group">
    <label class="control-label">Spam control</label>
  <div class="controls">
  <%= recaptcha_tags %>
  </div>
  </div>

  <%= f.actions do %>
    <%= f.primary 'Make reservation', disable_with: 'Reserving...' %>
  <% end %>

<% end %>
</section>

app/views/pre_reservations/success_one_place.html.erb
<section>
  <div class="page-header">
<h1>Pre-reservation acknowledgement</h1>
</div>

<p>You have pre-reserved your <%= @pre_reservation.resource_category %> place.</p>

<p>
  <b>You now have one hour</b> to complete your reservation (before <%= l @pre_reservations.first.expires_at %>).
</p>

<p>
  Make sure you complete the reservation form within an hour, <b>even if you
  get put on the waiting list at first</b>.
</p>

<p>
  All places will be allocated strictly in the order of pre-reservations, including waiting list places. 
</p>

<p>
  If you don't complete your reservation within one hour, your place will be cancelled
  and re-allocated to the next person (and you won't get put on the waiting list).
</p>

<p>We've sent you an email message containing a unique link which will allow you to return here, in case of any problem. </p>

<p>Your pre-reservation reference is <strong><%= @pre_reservation.reference %></strong></p>

<h2>&#x261e; <%= link_to "Complete your reservation", reservations_path(pre_reservation: @pre_reservation.reference) %></h2>

app/views/pre_reservations/waiting_list.html.erb
<section>
  <div class="page-header">
<h1>Waiting list</h1>
</div>

<p>Thanks, we've received your request and you've been added to our waiting list.</p>

<p>Your reference is <strong><%= @reservation.reference %></strong></p>

<p>We'll get in touch if a place becomes available.</p>

<p>You can come back to this page any time by using the following link:</p>
<p><%= link_to reservation_success_url @reservation.reference %></p>