config/routes.rb
SkintDance::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "/day_tickets/closed" => "day_ticket_orders#closed", as: :day_tickets_closed
  
  resources :day_ticket_orders, path: "day_tickets" do
  end

  resources :reservations do
    get :success
  end

  resources :pre_reservations do
    get :success
  end

  # get "reservations/success/:reference" => "reservations#success", as: "reservation_success"

  match ':action', controller: :pages
  root :to => 'pages#index'
end

app/views/admin/dashboard/_recent_reservations.html.erb
<ul>
  <% Reservation.in_resource_category(resource_category).group(:state).select("count(*) as count, state").order("state asc").each do |reservation_count_by_state| %>
    <li><%= reservation_count_by_state.state.humanize %>: <%= reservation_count_by_state.count %>
  <% end %>
  <li>Remaining places: <%= RESERVATION_MANAGER.remaining_places(resource_category) %></li>
  <li>Unexpired, unredeemed pre-reservations: 
    <%= link_to(RESERVATION_MANAGER.unexpired_pre_reservations(resource_category), "/admin/unexpired_prereservations?resource_category=#{resource_category}") %></li>
</ul>

<h3>Recent reservations</h3>
<table class="index_table">
  <thead>
    <th>Name</th>
    <th>Updated at</th>
    <th>State</th>
  </thead>
  <% Reservation.in_resource_category(resource_category).order("updated_at desc").limit(5).map do |reservation| %>
    <tr>
      <td>
        <%= link_to(reservation.name, admin_reservation_path(reservation)) %>
      </td>
      <td>
        <%= l reservation.updated_at %>
      </td>
      <td>
        <%= reservation.state %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/dashboard/_waiting_list.html.erb
<h3>Waiting list</h3>

<% places_available = RESERVATION_MANAGER.places_available_to_waiting_list(resource_category) %>
<p><%= pluralize(places_available, "place") %> available to waiting list.</p>

<table class="index_table">
  <thead>
    <th>Position</th>
    <th>PreReservation</th>
    <th>Name</th>
    <th>Reservation</th>
    <th>Date requested</th>
  </thead>
  <% RESERVATION_MANAGER.waiting_list(resource_category).limit(10).map.with_index do |waiting_list_entry, i| %>
    <tr>
      <td><%= i + 1%></td>
      <td>
        <%= waiting_list_entry.pre_reservation_id %>
      </td>
      <td>
        <%= link_to(waiting_list_entry.name, admin_waiting_list_entry_path(waiting_list_entry)) %>
      </td>
      <td>
        <%= link_to("#{waiting_list_entry.reservation.resource_category}", admin_reservation_path(waiting_list_entry.reservation)) %> (<%= waiting_list_entry.reservation.state %>)
      </td>
      <td>
        <%= l waiting_list_entry.added_at %>
      </td>
      <td>
        <% if RESERVATION_MANAGER.place_available_for?(waiting_list_entry.pre_reservation, resource_category) %>
          <%= button_to("Allocate place", allocate_admin_waiting_list_entry_path(waiting_list_entry)) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>